[tox]
minversion = 4.9.0
# environments that run when `tox` is invoked with no arguments
envlist =
    lint
    tests
    docs

lint_folders =
    "{toxinidir}/flatwalk" \
    "{toxinidir}/tests" \
    "{toxinidir}/examples" \
    "{toxinidir}/docs/src" \
    "{toxinidir}/docs/examples" \
    "{toxinidir}/docs/tutorials"

[testenv]
passenv = *

# default packaging env (for source distribution)
[testenv:.pkg]

# ---------------------------------------------------------------- tests
[testenv:tests]
description = Run the test suite with pytest under {basepython}.
setenv =
    PYTHONUNBUFFERED=yes
usedevelop = true
extras = test
commands =
    pytest {posargs}

# ---------------------------------------------------------------- lint
[testenv:lint]
description = Run linters and static checks.
package = skip
deps =
    ruff
    sphinx-lint
commands =
    ruff format --diff {[tox]lint_folders}
    ruff check {[tox]lint_folders}
    sphinx-lint \
        --enable all \
        --disable line-too-long \
        {toxinidir}/docs/src \
        {toxinidir}/README.md

# ---------------------------------------------------------------- format
# Abuse tox to actually rewrite files in place.
[testenv:format]
description = Format the codebase in place with ruff.
package = skip
deps = ruff
commands =
    ruff format {[tox]lint_folders}
    ruff check --fix-only {[tox]lint_folders} {posargs}

# ---------------------------------------------------------------- docs
[testenv:docs]
description = Build the Sphinx documentation.
usedevelop = true
extras = docs
commands =
    sphinx-build \
        {posargs:-E} \
        --builder html \
        --doctree-dir docs/build/doctree \
        --fail-on-warning \
        docs/src docs/build/html

# ---------------------------------------------------------------- build
[testenv:build]
description = Assert package build integrity for {platform} on {basepython}.
usedevelop = true
deps =
    build
    twine
allowlist_externals =
    bash
commands =
    python -m build
    twine check dist/*.tar.gz dist/*.whl
